response = {
    "list": [
        {
            "dt": 1724274000,
            "main": {
                "temp": 81.9,
                "feels_like": 80.94,
                "temp_min": 81.9,
                "temp_max": 88.75,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 986,
                "humidity": 36,
                "temp_kf": -3.81,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 8.41, "deg": 327, "gust": 7.4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-21 21:00:00",
        },
        {
            "dt": 1724284800,
            "main": {
                "temp": 83.43,
                "feels_like": 81.55,
                "temp_min": 83.43,
                "temp_max": 85.91,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 985,
                "humidity": 30,
                "temp_kf": -1.38,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 2},
            "wind": {"speed": 12.57, "deg": 315, "gust": 8.79},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-22 00:00:00",
        },
        {
            "dt": 1724295600,
            "main": {
                "temp": 66.51,
                "feels_like": 65.73,
                "temp_min": 66.51,
                "temp_max": 66.51,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 985,
                "humidity": 61,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 3},
            "wind": {"speed": 8.39, "deg": 302, "gust": 10.54},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-22 03:00:00",
        },
        {
            "dt": 1724306400,
            "main": {
                "temp": 59.76,
                "feels_like": 59.38,
                "temp_min": 59.76,
                "temp_max": 59.76,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 84,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 4.12, "deg": 299, "gust": 7.72},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-22 06:00:00",
        },
        {
            "dt": 1724317200,
            "main": {
                "temp": 57.18,
                "feels_like": 56.82,
                "temp_min": 57.18,
                "temp_max": 57.18,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 90,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 3.24, "deg": 282, "gust": 5.12},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-22 09:00:00",
        },
        {
            "dt": 1724328000,
            "main": {
                "temp": 56.5,
                "feels_like": 56.12,
                "temp_min": 56.5,
                "temp_max": 56.5,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 985,
                "humidity": 91,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 5},
            "wind": {"speed": 1.68, "deg": 263, "gust": 3.6},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-22 12:00:00",
        },
        {
            "dt": 1724338800,
            "main": {
                "temp": 61.05,
                "feels_like": 60.62,
                "temp_min": 61.05,
                "temp_max": 61.05,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 80,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 31},
            "wind": {"speed": 1.66, "deg": 242, "gust": 3.29},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-22 15:00:00",
        },
        {
            "dt": 1724349600,
            "main": {
                "temp": 73.85,
                "feels_like": 73.09,
                "temp_min": 73.85,
                "temp_max": 73.85,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 46,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 801,
                    "main": "Clouds",
                    "description": "few clouds",
                    "icon": "02d",
                }
            ],
            "clouds": {"all": 12},
            "wind": {"speed": 7.07, "deg": 311, "gust": 6.91},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-22 18:00:00",
        },
        {
            "dt": 1724360400,
            "main": {
                "temp": 78.33,
                "feels_like": 77.7,
                "temp_min": 78.33,
                "temp_max": 78.33,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 986,
                "humidity": 39,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 12.17, "deg": 320, "gust": 10.04},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-22 21:00:00",
        },
        {
            "dt": 1724371200,
            "main": {
                "temp": 76.14,
                "feels_like": 75.42,
                "temp_min": 76.14,
                "temp_max": 76.14,
                "pressure": 1013,
                "sea_level": 1013,
                "grnd_level": 985,
                "humidity": 42,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 11.86, "deg": 309, "gust": 10.83},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-23 00:00:00",
        },
        {
            "dt": 1724382000,
            "main": {
                "temp": 65.79,
                "feels_like": 65.21,
                "temp_min": 65.79,
                "temp_max": 65.79,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 985,
                "humidity": 67,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 6.69, "deg": 293, "gust": 10.4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-23 03:00:00",
        },
        {
            "dt": 1724392800,
            "main": {
                "temp": 60.62,
                "feels_like": 60.28,
                "temp_min": 60.62,
                "temp_max": 60.62,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 83,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 10},
            "wind": {"speed": 4.36, "deg": 289, "gust": 7.34},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-23 06:00:00",
        },
        {
            "dt": 1724403600,
            "main": {
                "temp": 57.87,
                "feels_like": 57.16,
                "temp_min": 57.87,
                "temp_max": 57.87,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 81,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 3.65, "deg": 301, "gust": 7.45},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-23 09:00:00",
        },
        {
            "dt": 1724414400,
            "main": {
                "temp": 55.8,
                "feels_like": 54.88,
                "temp_min": 55.8,
                "temp_max": 55.8,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 81,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 0.81, "deg": 204, "gust": 2.13},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-23 12:00:00",
        },
        {
            "dt": 1724425200,
            "main": {
                "temp": 60.33,
                "feels_like": 59.36,
                "temp_min": 60.33,
                "temp_max": 60.33,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 987,
                "humidity": 70,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 1.45, "deg": 257, "gust": 3.53},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-23 15:00:00",
        },
        {
            "dt": 1724436000,
            "main": {
                "temp": 68.85,
                "feels_like": 67.73,
                "temp_min": 68.85,
                "temp_max": 68.85,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 49,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.83, "deg": 316, "gust": 5.17},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-23 18:00:00",
        },
        {
            "dt": 1724446800,
            "main": {
                "temp": 71.11,
                "feels_like": 70,
                "temp_min": 71.11,
                "temp_max": 71.11,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 987,
                "humidity": 44,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 5.95, "deg": 329, "gust": 4.47},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-23 21:00:00",
        },
        {
            "dt": 1724457600,
            "main": {
                "temp": 75.9,
                "feels_like": 74.84,
                "temp_min": 75.9,
                "temp_max": 75.9,
                "pressure": 1014,
                "sea_level": 1014,
                "grnd_level": 985,
                "humidity": 35,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 10.51, "deg": 305, "gust": 7.65},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-24 00:00:00",
        },
        {
            "dt": 1724468400,
            "main": {
                "temp": 64.92,
                "feels_like": 63.84,
                "temp_min": 64.92,
                "temp_max": 64.92,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 986,
                "humidity": 58,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 94},
            "wind": {"speed": 7.49, "deg": 307, "gust": 10.94},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-24 03:00:00",
        },
        {
            "dt": 1724479200,
            "main": {
                "temp": 59.29,
                "feels_like": 58.73,
                "temp_min": 59.29,
                "temp_max": 59.29,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 81,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 53},
            "wind": {"speed": 1.88, "deg": 326, "gust": 3.74},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-24 06:00:00",
        },
        {
            "dt": 1724490000,
            "main": {
                "temp": 58.03,
                "feels_like": 57.52,
                "temp_min": 58.03,
                "temp_max": 58.03,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 987,
                "humidity": 85,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 5},
            "wind": {"speed": 1.48, "deg": 324, "gust": 2.04},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-24 09:00:00",
        },
        {
            "dt": 1724500800,
            "main": {
                "temp": 57.58,
                "feels_like": 57.16,
                "temp_min": 57.58,
                "temp_max": 57.58,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 88,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 6},
            "wind": {"speed": 1.43, "deg": 339, "gust": 2.46},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-24 12:00:00",
        },
        {
            "dt": 1724511600,
            "main": {
                "temp": 61.68,
                "feels_like": 61.21,
                "temp_min": 61.68,
                "temp_max": 61.68,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 989,
                "humidity": 78,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 6},
            "wind": {"speed": 3.2, "deg": 334, "gust": 5.77},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-24 15:00:00",
        },
        {
            "dt": 1724522400,
            "main": {
                "temp": 72.63,
                "feels_like": 71.71,
                "temp_min": 72.63,
                "temp_max": 72.63,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 989,
                "humidity": 45,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 5},
            "wind": {"speed": 7.81, "deg": 324, "gust": 7.07},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-24 18:00:00",
        },
        {
            "dt": 1724533200,
            "main": {
                "temp": 78.82,
                "feels_like": 78.82,
                "temp_min": 78.82,
                "temp_max": 78.82,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 33,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 9.33, "deg": 319, "gust": 7.45},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-24 21:00:00",
        },
        {
            "dt": 1724544000,
            "main": {
                "temp": 77.59,
                "feels_like": 76.69,
                "temp_min": 77.59,
                "temp_max": 77.59,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 988,
                "humidity": 35,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 12.1, "deg": 323, "gust": 9.57},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-25 00:00:00",
        },
        {
            "dt": 1724554800,
            "main": {
                "temp": 66.4,
                "feels_like": 65.52,
                "temp_min": 66.4,
                "temp_max": 66.4,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 59,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 9.66, "deg": 318, "gust": 15.88},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-25 03:00:00",
        },
        {
            "dt": 1724565600,
            "main": {
                "temp": 60.71,
                "feels_like": 59.86,
                "temp_min": 60.71,
                "temp_max": 60.71,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 989,
                "humidity": 72,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 2.42, "deg": 319, "gust": 6.42},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-25 06:00:00",
        },
        {
            "dt": 1724576400,
            "main": {
                "temp": 59.36,
                "feels_like": 58.19,
                "temp_min": 59.36,
                "temp_max": 59.36,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 68,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 1.1, "deg": 346, "gust": 2.1},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-25 09:00:00",
        },
        {
            "dt": 1724587200,
            "main": {
                "temp": 58.57,
                "feels_like": 57.18,
                "temp_min": 58.57,
                "temp_max": 58.57,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 65,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 0.22, "deg": 114, "gust": 1.32},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-25 12:00:00",
        },
        {
            "dt": 1724598000,
            "main": {
                "temp": 65.91,
                "feels_like": 64.56,
                "temp_min": 65.91,
                "temp_max": 65.91,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 989,
                "humidity": 50,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 0.87, "deg": 333, "gust": 0.89},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-25 15:00:00",
        },
        {
            "dt": 1724608800,
            "main": {
                "temp": 80.44,
                "feels_like": 79.45,
                "temp_min": 80.44,
                "temp_max": 80.44,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 990,
                "humidity": 30,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 5.12, "deg": 321, "gust": 4.59},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-25 18:00:00",
        },
        {
            "dt": 1724619600,
            "main": {
                "temp": 89.78,
                "feels_like": 86.13,
                "temp_min": 89.78,
                "temp_max": 89.78,
                "pressure": 1016,
                "sea_level": 1016,
                "grnd_level": 988,
                "humidity": 20,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 7.78, "deg": 319, "gust": 6.44},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-25 21:00:00",
        },
        {
            "dt": 1724630400,
            "main": {
                "temp": 88.84,
                "feels_like": 85.35,
                "temp_min": 88.84,
                "temp_max": 88.84,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 987,
                "humidity": 21,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 10.38, "deg": 324, "gust": 6.46},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-26 00:00:00",
        },
        {
            "dt": 1724641200,
            "main": {
                "temp": 74.14,
                "feels_like": 72.84,
                "temp_min": 74.14,
                "temp_max": 74.14,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 34,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 7.05, "deg": 328, "gust": 8.01},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-26 03:00:00",
        },
        {
            "dt": 1724652000,
            "main": {
                "temp": 67.8,
                "feels_like": 66.34,
                "temp_min": 67.8,
                "temp_max": 67.8,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 989,
                "humidity": 44,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 1.61, "deg": 327, "gust": 2.48},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-26 06:00:00",
        },
        {
            "dt": 1724662800,
            "main": {
                "temp": 66.07,
                "feels_like": 64.45,
                "temp_min": 66.07,
                "temp_max": 66.07,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 44,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 6},
            "wind": {"speed": 1.05, "deg": 58, "gust": 1.52},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-26 09:00:00",
        },
        {
            "dt": 1724673600,
            "main": {
                "temp": 65.34,
                "feels_like": 63.68,
                "temp_min": 65.34,
                "temp_max": 65.34,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 988,
                "humidity": 45,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 8},
            "wind": {"speed": 1.3, "deg": 345, "gust": 1.7},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2024-08-26 12:00:00",
        },
        {
            "dt": 1724684400,
            "main": {
                "temp": 71.71,
                "feels_like": 70.36,
                "temp_min": 71.71,
                "temp_max": 71.71,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 989,
                "humidity": 38,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 5},
            "wind": {"speed": 1.88, "deg": 324, "gust": 1.81},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-26 15:00:00",
        },
        {
            "dt": 1724695200,
            "main": {
                "temp": 87.19,
                "feels_like": 83.97,
                "temp_min": 87.19,
                "temp_max": 87.19,
                "pressure": 1017,
                "sea_level": 1017,
                "grnd_level": 989,
                "humidity": 22,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 2},
            "wind": {"speed": 5.73, "deg": 322, "gust": 3.91},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2024-08-26 18:00:00",
        },
    ],
}