[
    {
        "name": "San Jose",
        "local_names": {
            "en": "San Jose",
            "oc": "San José",
            "pt": "San José",
            "uk": "Сан-Хосе",
            "zh": "聖荷西",
            "ar": "سان خوسيه",
            "ru": "Сан-Хосе",
            "eo": "San-Joseo",
            "es": "San José",
            "gl": "San Xosé",
            "vi": "San Jose",
            "am": "ሳን ሆዜ",
        },
        "lat": 37.3361663,
        "lon": -121.890591,
        "country": "US",
        "state": "California",
    },
    {
        "name": "San José",
        "local_names": {
            "eo": "San-Joseo",
            "be": "Сан-Хасэ",
            "fa": "سان خوزه",
            "th": "ซันโโฮเซ",
            "lt": "San Chosė",
            "nn": "San José i Costa Rica",
            "az": "San-Xose",
            "el": "Σαν Χοσέ",
            "fr": "San José",
            "gl": "San Xosé, Costa Rica",
            "ar": "سان خوسيه، كوستاريكا",
            "nl": "San José",
            "he": "סן חוסה",
            "en": "San José",
            "bg": "Сан Хосе",
            "hu": "San José",
            "ug": "سان خوسې",
            "zh": "聖荷西",
            "pl": "San José",
            "os": "Сан-Хосе",
            "bn": "স্যান হোসে, কোস্টা রিকা",
            "ka": "სან-ხოსე",
            "mr": "सान होजे, कोस्टा रिका",
            "ta": "சான் ஹொசே, கோஸ்ட்      டா ரிக்கா",
            "is": "San José",
            "sv": "San José, Costa Rica",
            "mk": "Сан Хозе",
            "es": "San José",
            "bo": "སན་ཇོ་སེ།",
            "hy": "Սան Խոսե",
            "ja": "サン    ホセ",
            "lv": "Sanhosē",
            "bs": "San Jose, Kostarika",
            "de": "San José",
            "am": "ሳን ሆዜ",
            "ht": "San Jozé",
            "uk": "Сан-Хосе",
            "sr": "Сан Хосе",
            "io": "San Jose",
            "sw": "San Jose",
            "hi": "सान होज़े",
            "ur": "سان ہوزے",
            "ko": "산호세",
            "ru": "Сан-Хосе",
        },
        "lat": 9.9325427,
        "lon": -84.0795782,
        "cou untry": "CR",
    },
    {
        "name": "San Jose",
        "lat": 12.0612933,
        "lon": 121.9565754,
        "country": "PH",
        "state": "Romblon",
    },
    {
        "name": "Sant Josep de sa Talaia",
        "local_names": {"ca": "Sant Josep de sa Talaia", "es": "San José"},
        "lat": 38.9043608,
        "lon": 1.3178098,
        "country": "ES",
        "state": "Balearic Islands",
    },
    {
        "name": "San Jose",
        "local_names": {"en": "San Jose"},
        "lat": 40.305598,
        "lon": -89.6028829,
        "country": "US",
        "state": "Illinois",
    },
]



"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_KEY}&units=imperial"
{
    "coord": {"lon": -121.895, "lat": 37.3394},
    "weather": [
        {"id": 800, 
         "main": "Clear", 
         "description": "clear sky", 
         "icon": "01d"}
    ],
    "base": "stations",
    "main": {
        "temp": 75.96,
        "feels_like": 75.51,
        "temp_min": 72.79,
        "temp_max": 79.83,
        "pressure": 1017,
        "humidity": 48,
        "sea_level": 1017,
        "grnd_level": 988,
    },
    "visibility": 10000,
    "wind": {"speed": 5.75, "deg": 330},
    "clouds": {"all": 0},
    "dt": 1724263548,
    "sys": {
        "type": 2,
        "id": 2004102,
        "country": "US",
        "sunrise": 1724246973,
        "sunset": 1724295117,
    },
    "timezone": -25200,
    "id": 5392171,
    "name": "San Jose",
    "cod": 200,
}
